### ISSUE TITLE
Cloundinary configuration error

### ISSUE THREAD

**Issue by ardiadrianadri** [everisARQ/keystonejs-portal#17]
Hello:

 I think I'm missing something in the keystone configuration. When I run the keystone.js I get this error:

```
Error: Invalid Configuration

CloudinaryImage fields (Gallery.heroImage) require the "cloudinary config" option to be set.

See http://keystonejs.com/docs/configuration/#services-cloudinary for more information.

    at new cloudinaryimage (/home/ardi/Cursos/alt-arq/keystonejs-portal/node_modules/keystone/fields/types/cloudinaryimage/CloudinaryImageType.js:34:9)
    at List.field (/home/ardi/Cursos/alt-arq/keystonejs-portal/node_modules/keystone/lib/list/field.js:46:14)
    at List.<anonymous> (/home/ardi/Cursos/alt-arq/keystonejs-portal/node_modules/keystone/lib/list/add.js:41:16)
    at List.<anonymous> (/home/ardi/Cursos/alt-arq/keystonejs-portal/node_modules/keystone/lib/list/add.js:30:5)
    at List.<anonymous> (/home/ardi/Cursos/alt-arq/keystonejs-portal/node_modules/keystone/lib/list/add.js:71:5)
    at /home/ardi/Cursos/alt-arq/keystonejs-portal/node_modules/underscore/underscore.js:73:21
    at Function._.each._.forEach (/home/ardi/Cursos/alt-arq/keystonejs-portal/node_modules/underscore/underscore.js:153:9)
    at List.add (/home/ardi/Cursos/alt-arq/keystonejs-portal/node_modules/keystone/lib/list/add.js:45:4)
    at Object.<anonymous> (/home/ardi/Cursos/alt-arq/keystonejs-portal/models/Gallery.js:13:9)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at /home/ardi/Cursos/alt-arq/keystonejs-portal/node_modules/keystone/index.js:185:23
```

Does anyone have the same problem?

**Comment by telco2011** [comment]
You can try to rename .env_test to .env. This file is necessary to run keystonejs. This feature we could try to change it.
