### ISSUE TITLE
Error 404 for file generalConfig.js

### ISSUE THREAD

**Issue by ardiadrianadri** [everisARQ/keystonejs-portal#28]
When I try to access at the home of keystonejs-portal, I get a 404 error because the browser can't find the file app/resource/generalConfig.js. As consequence, the module GeneralConfig is not loaded in the context of angular and it throw an injection exception

This is the log error:
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught Error: [$injector:modulerr] Failed to instantiate module Router due to:
Error: [$injector:modulerr] Failed to instantiate module GeneralConfig due to:
Error: [$injector:nomod] Module 'GeneralConfig' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.3.15/$injector/nomod?p0=GeneralConfig
    at http://localhost:3000/libs/angular/angular.js:63:12
    at http://localhost:3000/libs/angular/angular.js:1774:17
    at ensure (http://localhost:3000/libs/angular/angular.js:1698:38)
    at module (http://localhost:3000/libs/angular/angular.js:1772:14)
    at http://localhost:3000/libs/angular/angular.js:4115:22
    at forEach (http://localhost:3000/libs/angular/angular.js:323:20)
    at loadModules (http://localhost:3000/libs/angular/angular.js:4099:5)
    at http://localhost:3000/libs/angular/angular.js:4116:40
    at forEach (http://localhost:3000/libs/angular/angular.js:323:20)
    at loadModules (http://localhost:3000/libs/angular/angular.js:4099:5)
http://errors.angularjs.org/1.3.15/$injector/modulerr?p0=GeneralConfig&p1=E…%20(http%3A%2F%2Flocalhost%3A3000%2Flibs%2Fangular%2Fangular.js%3A4099%3A5)
    at http://localhost:3000/libs/angular/angular.js:63:12
    at http://localhost:3000/libs/angular/angular.js:4138:15
    at forEach (http://localhost:3000/libs/angular/angular.js:323:20)
    at loadModules (http://localhost:3000/libs/angular/angular.js:4099:5)
    at http://localhost:3000/libs/angular/angular.js:4116:40
    at forEach (http://localhost:3000/libs/angular/angular.js:323:20)
    at loadModules (http://localhost:3000/libs/angular/angular.js:4099:5)
    at createInjector (http://localhost:3000/libs/angular/angular.js:4025:11)
    at doBootstrap (http://localhost:3000/libs/angular/angular.js:1452:20)
    at bootstrap (http://localhost:3000/libs/angular/angular.js:1473:12)
http://errors.angularjs.org/1.3.15/$injector/modulerr?p0=Router&p1=Error%3A…20(http%3A%2F%2Flocalhost%3A3000%2Flibs%2Fangular%2Fangular.js%3A1473%3A12)

**Comment by ArnauAregall** [comment]
Can't reproduce the error.
AFAIK the project does _not_ use `angular`... I can't figure out where this stacktrace comes from :no_mouth:

**Comment by ardiadrianadri** [comment]
Ok, my fault. The browser cache plays tricks with me. Sorry
